spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/dbname?characterEncoding=utf-8&allowMultiQueries=true
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver

server:
  port: 8081

